-- بذرة الاستطلاعات (مولّدة من نماذج docx الرسمية)
-- شغّلها بعد schema.sql في SQL Editor

do $$
declare sid uuid; aid uuid;
begin

  -- استطلاع رأي الطلاب حول جودة البرنامج (student/master)
  insert into survey_templates (title_ar, audience, degree_level, language, is_recurring) values ('استطلاع رأي الطلاب حول جودة البرنامج', 'student', 'master', 'ar', true) returning id into sid;
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور خصائص الخريجين ونواتج تعلم البرنامج', 0) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أسهم البرنامج في إكسابي المعرفة المتعمقة في مجال تخصصي', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أسهم البرنامج في إكسابي المهارات المعرفية (مهارات التفكير وحل المشكلات واتخاذ القرار... إلخ) المتعمقة في مجال تخصصي', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أسهم البرنامج في إكسابي مهارات العلاقات الشخصية وتحمل المسؤولية (المبادرة، والالتزام، والقيادة، والعمل في فريق، والعمل الفردي... إلخ) المتعمقة في مجال تخصصي', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أسهم البرنامج في إكسابي مهارات التواصل والمهارات التقنية والمهارات العددية (مهارات الاتصال الفعال، واستخدام التقنية، وتصميم العروض التقديمية، والمعالجات الإحصائية... إلخ) المتعمقة في مجال تخصصي', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أسهم البرنامج في إكسابي القيم والأخلاقيات (الصدق، الأمانة، الموضوعية، الإخلاص... إلخ) المتعمقة في مجال تخصصي', 4);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور  جودة إدارة البرنامج', 1) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تعمل إدارة البرنامج على توفير بيئة أكاديمية داعمة', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتوفر قدر كافٍ من المرونة والصلاحيات تسمح للقائمين على البرنامج بإحداث التطوير والتغيير اللازم', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تطبق إدارة البرنامج آليات تضمن النزاهة والعدالة والمساواة في جميع ممارساتها', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتيح إدارة البرنامج معلومات موثوقة ومعلنة تتضمن وصف البرنامج، وأدائه وإنجازاته', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تشجع إدارة البرنامج المبادرات والمقترحات التطويرية للبرنامج', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تلتزم إدارة البرنامج بتفعيل قيم الأمانة العلمية والممارسات الأخلاقية في المجالات الأكاديمية والبحثية والإدارية والخدمية', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تطبق إدارة البرنامج الأنظمة واللوائح والإجراءات المعتمدة من قبل الجامعة والكلية والقسم، بما في ذلك: التظلم، والشكاوى، والقضايا التأديبية', 6);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور ضمان جودة البرنامج', 2) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تطبق إدارة البرنامج نظاماً فعالاً لضمان الجودة وإدارتها', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يشارك الطلاب في عمليات التخطيط وضمان الجودة وصنع القرار', 1);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور المنهج واستراتيجيات التعليم والتعلم وطرق التقييم', 3) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تحقق المناهج الدراسية أهداف البرنامج ومخرجاته التعليمية', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تواكب المناهج الدراسية التطورات العلمية والتقنية والمهنية في مجال التخصص', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتوافق استراتيجيات التعليم والتعلم، وطرق التقييم المستخدمة مع مخرجات التعلم المستهدفة', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتنوع استراتيجيات التعليم والتعلم وطرق التقييم في البرنامج', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تعزز استراتيجيات التعليم والتعلم وطرق التقييم في البرنامج القدرة على إجراء البحوث العلمية', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تضمن استراتيجيات التعليم والتعلم وطرق التقييم في البرنامج اكتساب الطلبة لمهارات التفكير العليا والتعلم الذاتي', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يلتزم عضو هيئة التدريس باستراتيجيات التعليم والتعلم وطرق التقييم الواردة في توصيفات البرنامج والمقررات', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يُزوَّد الطلاب في بداية الدراسة بمعلومات شاملة عن المقرر (توصيف المقرر)', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يطبق البرنامج إجراءات واضحة ومعلنة للتحقق من جودة طرق التقييم ومصداقيتها', 8);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يطبق البرنامج إجراءات واضحة ومعلنة للتأكد من مستوى تحصيل الطلاب', 9);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يطبق البرنامج إجراءات فعّالة للتحقق من أن الأعمال والواجبات والبحوث التي يقدمها الطلاب هي من إنتاجهم', 10);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تُقدَّم تغذية راجعة للطلاب عن أدائهم ونتائج تقويمهم في وقت يمكنهم فيه من تحسين أدائهم', 11);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يشجع البرنامج إثراء خبرات الطلاب بإتاحة فرص متنوعة للتبادل الطلابي والزيارات والمنح والالتحاق بالمراكز البحثية والتدريبية المتميزة', 12);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور الإرشاد الأكاديمي', 4) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'المرشد الأكاديمي متواجد حين أحتاجه', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'ساعدني المرشد الأكاديمي في تنظيم جدولي الدراسي', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'المرشد الأكاديمي يمتلك المهارة والمعرفة لدعمي', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أشعر بالرضا بوجه عام عن المرشد الأكاديمي', 3);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور المكتبة', 5) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'استفدت من الخدمات التي تقدمها المكتبة المركزية بالجامعة في دعم التعلم والبحث العلمي', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتوفر في المكتبة العدد الكافي من المصادر المتنوعة التي يسهل الوصول إليها، والتي تتناسب مع احتياجات البرنامج', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتاح لشطري الطلاب والطالبات في المكتبة المصادر التي تتناسب مع احتياجات البرنامج في أوقات مناسبة وكافية', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'استفدت من قواعد البيانات العربية والأجنبية المتاحة من خلال المكتبة الرقمية السعودية في دعم تعليمي وإجرائي للبحوث والتكليفات العلمية', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'استفدت من الدورات التدريبية الإلكترونية المتنوعة التي تقدمها المكتبة الرقمية السعودية في دعم مهاراتي وقدراتي البحثية', 4);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور تقنية المعلومات', 6) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم استخدام التقنية بفاعلية في دعم التعليم والتعلم والبحث العلمي بالبرنامج', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتوفر الدعم الفني الذي أحتاجه لاستخدام مصادر التعلم الإلكترونية وقواعد البيانات ونظام إدارة التعلم الإلكتروني (البلاكبورد)', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتوفر للبرنامج التجهيزات الحاسوبية والتقنية الملائمة للتخصص والكافية لإجراء البحوث والدراسات العلمية', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتم صيانة التجهيزيات الحاسوبية والتقنية المتاحة بشكل دوري', 3);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور الأنشطة والخدمات الجامعية', 7) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'توفر الجامعة أنشطة مختلفة (رياضية، وترفيهية، وثقافية، واجتماعية) تلبي احتياجاتي', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'خدمات تقنية المعلومات التي توفرها الجامعة (الإنترنت، والمكتبة الرقمية، والبلاكبورد ... إلخ) تلبي احتياجاتي', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تُوفر الجامعة خدمات كافية ومناسبة للنقل والإسكان والمطاعم.', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تُوفر الجامعة مرافق مستوفية لمتطلبات الصحة والنظافة مناسبة لجميع منسوبيها بما فيهم ذوي الإعاقة لممارسة كافة الأنشطة العلمية والثقافية والرياضية والترفيهية والدينية.', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تُوفر الجامعة الرعاية والخدمات المناسبة بما في ذلك الرعاية الصحية الطارئة.', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أشعر بالرضا بشكل عام عن مستوى الخدمات المقدمة طوال دراستي بالبرنامج.', 5);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور القاعات الدراسية وتجهيزاتها', 8) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتوفر للبرنامج القاعات الدراسية والمرافق المناسبة لاحتياجاته', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتوفر بالقاعات الدراسية التجهيزات المناسبة لتدريس مقررات البرنامج (أجهزة حاسب وأجهزة عرض إلكتروني وشاشات عرض وسبورات بيضاء... إلخ).', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتميز قاعات الدراسة بظروف فيزيقية مناسبة مثل: التهوية والإضاءة والبعد عن الضوضاء', 2);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور مصادر التعلم', 9) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'مصادر التعليم والتعلم بالبرنامج كافية ومناسبة', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'مصادر التعليم والتعلم بالبرنامج متنوعة ويسهل الوصول إليها', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'مصادر التعليم والتعلم مرتبطة ارتباطًا وثيقًا بمخرجات تعلم البرنامج', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'استفدت بشكل كبير من مصادر التعليم والتعلم المتاحة بالبرنامج', 3);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'التقويم العام للبرنامج', 10) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أشعر بالرضا بشكل عام عن مستوى جودة البرنامج الأكاديمي', 0);

  -- استطلاع رأي أعضاء هيئة التدريس حول جودة البرنامج (faculty/master)
  insert into survey_templates (title_ar, audience, degree_level, language, is_recurring) values ('استطلاع رأي أعضاء هيئة التدريس حول جودة البرنامج', 'faculty', 'master', 'ar', true) returning id into sid;
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور  جودة إدارة البرنامج', 0) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تعمل إدارة البرنامج على توفير بيئة أكاديمية داعمة', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتوفر قدر كافٍ من المرونة والصلاحيات تسمح للقائمين على البرنامج بإحداث التطوير والتغيير اللازم', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تطبق إدارة البرنامج آليات تضمن النزاهة والعدالة والمساواة في جميع ممارساتها', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تلتزم إدارة البرنامج بتنمية وتطوير المهارات والقدرات المهنية لهيئة التدريس في مجال التخصص', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتيح إدارة البرنامج معلومات موثوقة ومعلنة تتضمن وصف البرنامج، وأدائه وإنجازاته', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تشجع إدارة البرنامج المبادرات والمقترحات التطويرية للبرنامج', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يطبق البرنامج نظامًا فعالاً لتقويم أداء القيادات وهيئة التدريس وفق معايير وآليات واضحة ومعلنة', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تلتزم إدارة البرنامج بتفعيل قيم الأمانة العلمية والممارسات الأخلاقية في المجالات الأكاديمية والبحثية والإدارية والخدمية', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تطبق إدارة البرنامج الأنظمة واللوائح والإجراءات المعتمدة من قبل الجامعة والكلية والقسم، بما في ذلك: التظلم، والشكاوى، والقضايا التأديبية', 8);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتوفر للبرنامج التمويل المالي الكافي لتحقيق رسالته وأهدافه مع وجود آليات لتحديد أولويات الإنفاق', 9);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور ضمان جودة البرنامج', 1) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تطبق إدارة البرنامج نظاماً فعالاً لضمان الجودة وإدارتها', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يشارك أعضاء هيئة التدريس والطلاب في عمليات التخطيط وضمان الجودة وصنع القرار', 1);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور  الخطة الدراسية والمنهج', 2) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تراعي الخطة الدراسية التتابع والتكامل بين المقررات الدراسية والأنشطة العلمية', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تحقق الخطة الدراسية التوازن بين الجوانب النظرية والتطبيقية والمكون البحثي، والعمق العلمي', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تُحدد المكونات البحثية ضمن الخطة الدراسية للبرنامج بصورة واضحة', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تحقق المناهج الدراسية أهداف البرنامج ومخرجاته التعليمية', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تواكب المناهج الدراسية التطورات العلمية والتقنية والمهنية في مجال التخصص', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتوافق استراتيجيات التعليم والتعلم، وطرق التقييم المستخدمة مع مخرجات التعلم المستهدفة', 5);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور جودة التعليم وتقييم الطلاب', 3) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتنوع استراتيجيات التعليم والتعلم وطرق التقييم في البرنامج', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تعزز استراتيجيات التعليم والتعلم وطرق التقييم في البرنامج القدرة على إجراء البحوث العلمية', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تضمن استراتيجيات التعليم والتعلم وطرق التقييم في البرنامج اكتساب الطلبة لمهارات التفكير العليا والتعلم الذاتي', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يلتزم عضو هيئة التدريس باستراتيجيات التعليم والتعلم وطرق التقييم الواردة في توصيفات البرنامج والمقررات', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يُقدَّم التدريب اللازم لهيئة التدريس على استراتيجيات التعليم والتعلم وطرق التقييم المحددة في توصيف البرنامج والمقررات', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يُقدَّم التدريب اللازم لهيئة التدريس على الاستخدام الفعال للتقنية الحديثة والمتطورة', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يُزوَّد الطلاب في بداية الدراسة بمعلومات شاملة عن المقرر (توصيف المقرر)', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تُقوَّم المقررات والأنشطة التعليمية بشكل دوري للتحقق من فاعلية إستراتيجيات التعليم والتعلم وطرق التقييم', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يطبق البرنامج آليات لدعم وتحفيز التميز في التدريس والإشراف العلمي وتشجيع الإبداع والابتكار لدى هيئة التدريس', 8);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يسهم الإنتاج العلمي لأعضاء هيئة التدريس في إثراء المحتوى الدراسي في البرنامج', 9);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يطبق البرنامج إجراءات واضحة ومعلنة للتحقق من جودة طرق التقييم ومصداقيتها', 10);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يطبق البرنامج إجراءات واضحة ومعلنة للتأكد من مستوى تحصيل الطلاب', 11);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يطبق البرنامج إجراءات فعّالة للتحقق من أن الأعمال والواجبات والبحوث التي يقدمها الطلاب هي من إنتاجهم', 12);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تُقدَّم تغذية راجعة للطلاب عن أدائهم ونتائج تقويمهم في وقت يمكنهم فيه من تحسين أدائهم', 13);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يشجع البرنامج إثراء خبرات الطلاب بإتاحة فرص متنوعة للتبادل الطلابي والزيارات والمنح والالتحاق بالمراكز البحثية والتدريبية المتميزة', 14);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور  هيئة التدريس', 4) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يوفر البرنامج التهيئة المناسبة لهيئة التدريس الجدد والمتعاونين', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يشارك أعضاء هيئة التدريس بانتظام في أنشطة أكاديمية وبحثية', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يشارك أعضاء هيئة التدريس في أنشطة الشراكة المجتمعية', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتلقى أعضاء هيئة التدريس برامج في التطوير المهني والأكاديمي وجودة الإشراف العلمي', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يشارك أعضاء هيئة التدريس في أنشطة تقويم وتطوير البرنامج والمؤسسة', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تطبق آليات فعـَّالة لتقويم كفاية وجودة الخدمات المقدمة لهيئة التدريس وقياس رضاهم عنها', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يُقيَّم أداء أعضاء هيئة التدريس بانتظام وفق معايير محددة ومعلنة', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تقدم التغذية الراجعة لأعضاء هيئة التدريس في ضوء نتائج تقييم أدائهم', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يطبق البرنامج سياسات وإجراءات واضحة تضمن كفاية ومناسبة مصادر التعلم والبحث العلمي', 8);

  -- استطلاع رأي الخريجين حول جودة البرنامج (graduate/master)
  insert into survey_templates (title_ar, audience, degree_level, language, is_recurring) values ('استطلاع رأي الخريجين حول جودة البرنامج', 'graduate', 'master', 'ar', true) returning id into sid;
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور  المعرفة والمهارات الإدراكية', 0) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أمدتني دراستي بالبرنامج بمعرفة متعمقة بالنظريات والتطبيقات في مجال تخصصي', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أمدتني دراستي بالبرنامج بالقدرة على ربط النظرية بالتطبيق في مجال عملي', 1);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور  المهارات الشخصية', 1) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أكسبتني الدراسة بالبرنامج مهارات إدارة الوقت بكفاءة', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'اكتسبت روح المبادرة من خلال دراستي بالبرنامج', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أمدتني دراستي بالبرنامج بمعرفة متعمقة بالنظريات والتطبيقات في مجال تخصصي', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أمدتني دراستي بالبرنامج بالقدرة على ربط النظرية بالتطبيق في مجال عملي', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أكسبتني دراستي بالبرنامج القدرة على جمع وتحليل البيانات والمعلومات وطرح البدائل لحل المشكلات', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أكسبتني الدراسة بالبرنامج مهارات العمل بفاعلية كعضو في فرق العمل', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أمدتني دراستي بالبرنامج بالقدرة على التواصل ومهارات التحدث والحوار في مجال تخصصي', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'ساهمت دراستي بالبرنامج في تمتعي بشخصية قيادية', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أمدتني دراستي بالبرنامج بالقدرة على العمل باستقلالية', 8);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور مهارات العمل', 2) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'ساهمت دراستي بالبرنامج في تنمية قدرتي على تحمل الضغوط والتعامل مع الأزمات', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أمدتني الدراسة بالبرنامج بالقدرات المهنية الملائمة لعملي', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أكسبتني الدراسة بالبرنامج قيم وأخلاقيات إيجابية بمجال العمل', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أكسبتني الدراسة بالبرنامج مهارات الإبداع والتفكير الابتكاري في مجال عملي', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أكسبتني الدراسة بالبرنامج مهارات البحث العلمي', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أكسبتني الدراسة بالبرنامج مهارات التعلم الذاتي والمستمر', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أكسبتني الدراسة بالبرنامج القدرة على الإنجاز في مجال عمله', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'ساهمت دراستي بالبرنامج في تنمية احترام المواعيد والانضباط الوظيفي', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أكسبتني الدراسة بالبرنامج مهارات المعالجة الإحصائية للبيانات', 8);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور التواصل مع البرنامج', 3) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتواصل المسؤولون بالبرنامج معي بشكل فعال', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتم دعوتي من قبل المسؤولين بالبرنامج للمشاركة في مناسبات البرنامج وأنشطته المختلفة', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم استطلاع رأيي من قبل المسؤولين بالبرنامج حول التطوير الذي يتم بالبرنامج ومقرراته', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'أتواصل مع المسؤولين بالبرنامج لتحديث بياناتي بشكل مستمر', 3);

  -- استطلاع رأي الموظفين حول جودة البرنامج (employee/master)
  insert into survey_templates (title_ar, audience, degree_level, language, is_recurring) values ('استطلاع رأي الموظفين حول جودة البرنامج', 'employee', 'master', 'ar', true) returning id into sid;
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور السلطات والإدارة', 0) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم تزويدي بتغذية راجعة منتظمة تضمن تحسن أدائي في العمل', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتاح للموظفين المشاركة في عمليات التخطيط وتبادل الآراء', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يوجد دليل موضح فيه كل الأنظمة والإجراءات الداخلية اللازمة للقيام بالعمل', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم تحديد الصلاحيات والمسئوليات للجان الرئيسية (أو الدائمة) وللوظائف الإدارية والأكاديمية داخل الجامعة ويكون ذلك متضمنا في دليل السياسات والإجراءات.', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم الاعتراف والتقدير لجهودي المتميزة في العمل', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم إشعار الموظفين بالجامعة وبصورة منتظمة بالأحداث والخطط والتطورات التي تحدث فيها', 5);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور إدارة ضمان الجودة وتحسينها', 1) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم تشجيع الابتكار والإبداع في إطار من السياسات الواضحة على كافة المستويات في الجامعة.', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تدمج عمليات التقويم والتخطيط  للتحسين في عمليات التخطيط المعتادة وتصبح جزءا منها.', 1);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور  المرافق والتجهيزات', 2) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتوفر متطلبات الصحة والسلامة  في المرافق والتجهيزات', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يوجد نظام لتلقي التغذية الراجعة من الموظفين حول كفاية المرافق والتجهيزات', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتوفر أماكن مناسبة لأداء الواجبات الدينية لمنسوبي الجامعة', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'مرافق تقديم الطعام ملائمة لاحتياجات العاملين بالجامعة', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'خدمات الأمن والسلامة كافية لضمان سلامة الموظفين', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'خدمات الأمن والسلامة كافية لضمان سلامة مرافق الجامعة', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتوفر فرص التدريب المناسبة للموظفين وفق احتياجاتهم المهنية', 6);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور عمليات التوظيف', 3) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يوجد نظام لتقويم أداء الموظفين بالجامعة', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تتسم المشاورات التي يقوم بها المشرفون على الأداء الوظيفي (بما في ذلك العمداء ورؤساء الأقسام والمشرفون الإداريون وغيرهم) بالإيجابية والسرية.', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم تحديد مجالات التطوير في أدائي لمهامي الوظيفية المطلوبة.', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم تقدير الأداء الإداري المتميز للموظفين على مختلف المستويات', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يحصل الموظفون على فرص مناسبة للتطوير الوظيفي والتدريب', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'إجراءات التعيين مناسبة', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'قواعد الترقي مناسبة', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يوجد نظام فعال لتلقي الشكاوى والتظلم وحل النزاعات', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'نظام الرواتب والبدلات جيد وفعال', 8);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تقدم الجامعة دعما اجتماعيا مناسبا للموظفين', 9);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'حجم العمل الذي أقوم به متناسب مع ما أتقاضاه ماديا', 10);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتم معاملتي بطريقة لائقة', 11);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور المقترحات العامة', 4) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'نأمل توضيح وجهة نظرك العامة نحو رضاك الوظيفي عن الجامعة', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'نأمل ذكر أهم الاقتراحات التي تراها هامة لزيادة رضا الموظفين عن الجامعة من وجهة نظرك الشخصية', 1);

  -- استطلاع رأي جهات التوظيف حول جودة البرنامج (employer/master)
  insert into survey_templates (title_ar, audience, degree_level, language, is_recurring) values ('استطلاع رأي جهات التوظيف حول جودة البرنامج', 'employer', 'master', 'ar', true) returning id into sid;
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور المعرفة والمهارات الإدراكية', 0) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يمتلك الخريج معرفة متعمقة بالنظريات والتطبيقات في مجال تخصصه', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يمتلك الخريج القدرة على ربط النظرية بالتطبيق في مجال عمله', 1);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور المهارات الشخصية', 1) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتميز الخريج بالقدرة على جمع وتحليل البيانات والمعلومات وطرح البدائل لحل المشكلات', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتسم الخريج بالقدرة على التواصل ومهارات التحدث والحوار', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتمتع الخريج بشخصية قيادية', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يمتلك الخريج مهارات العمل في فريق', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يمتلك الخريج مهارات إدارة الوقت بكفاءة', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتسم الخريج بروح المبادرة', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يستطيع الخريج العمل باستقلالية', 6);
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محور مهارات العمل', 2) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتحمل الخريج الضغوط ويجيد التعامل مع الأزمات', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يمتلك الخريج القدرات المهنية الملائمة للعمل', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يمتلك الخريج مهارات الإبداع والتفكير الابتكاري في مجال العمل', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يمتلك الخريج مهارات المعالجة الإحصائية للبيانات', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يستطيع الخريج تنفيذ بحوث إجرائية بكفاءة', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يمتلك الخريج مهارات التعلم الذاتي والمستمر', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتحلى الخريج بالقيم والأخلاقيات الإيجابية', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يمتلك الخريج القدرة على الإنجاز في مجال العمل', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتسم الخريج باحترام المواعيد والانضباط الوظيفي', 8);

  -- استطلاع رأي الطلاب حول جودة الإشراف العلمي للرسائل الجامعية (supervision/master)
  insert into survey_templates (title_ar, audience, degree_level, language, is_recurring) values ('استطلاع رأي الطلاب حول جودة الإشراف العلمي للرسائل الجامعية', 'supervision', 'master', 'ar', true) returning id into sid;
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محاور الاستطلاع', 0) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يقدم لي المشرف الإجابات الكافية عن استفساراتي وتساؤلاتي البحثية', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يرشدني المشرف للأدبيات ولمصادر المعلومات والمراجع المنتمية لموضوع دراستي.', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يساعدني المشرف في تنظيم الرسالة وفق النظام المتبع في البرنامج', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يقوم المشرف بمراجعة وتقييم ما أكتبه من ناحية علمية', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يقدم لي المشرف التغذية الراجعة اللازمة', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يرشدني المشرف لطرق الاقتباس والتوثيق المتبعة', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يسهم المشرف في تطوير قدراتي ومهاراتي البحثية', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يشعرني المشرف بالتعديلات والتطورات الناتجة عن اجتماعات لجان الدراسات العليا في البرنامج', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يضع لي المشرف جدولا زمنيا لإنجاز الرسالة في مدة مناسبة،', 8);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يرشدني المشرف للإجراءات الإدارية المطلوبة في مرحلة الرسالة وخطوات إجرائها', 9);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'ينظم لي المشرف لقاءات إشراقية وتوجيهية كافية', 10);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يبلغني المشرف بمواعيد مناقشة الرسائل والبحوث العلمية ويحثني على الحضور', 11);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يبلغني المشرف بمواعيد المؤتمرات ذات العلاقة بموضوع البحث ويحثني على حضورها أو متابعته', 12);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يظهر المشرف المودة لطلبته الباحثين ويكوّن علاقات ودّ واحترام معهم', 13);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'ييسر المشرف العمل على طلبته ويساعدهم على تخطي بعض الصعوبات التي تواجههم', 14);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يقدر المشرف طلبته ويحترم آرائهم', 15);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يلتزم المشرف بالمواعيد التي يحددها لملاقاة طلبته', 16);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يشجع المشرف طلبته ويثني على جهودهم', 17);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يعزز المشرف ثقة الطالب بنفسه', 18);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'المتوسط العام', 19);

  -- استطلاع رأي الطلاب حول جودة التدريب الميداني (trainee/bachelor)
  insert into survey_templates (title_ar, audience, degree_level, language, is_recurring) values ('استطلاع رأي الطلاب حول جودة التدريب الميداني', 'trainee', 'bachelor', 'ar', true) returning id into sid;
  insert into survey_axes (survey_id, title_ar, position) values (sid, 'محاور الاستطلاع', 0) returning id into aid;
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يوجد دليل يوزع علي الطلاب المتدربين يوضح المهام في برنامج التدريب الميداني', 0);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'برامج التدريب الميداني فعالة في تطوير مهاراتي.', 1);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تلقيت اعداداً كافيا فبل التدريب الميداني', 2);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تم توجيهي الي مكان تدريب مناسب لتخصصي', 3);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'وفر لي مشرف الجامعة الاختيارات والمعلومات المناسبة في التدريب', 4);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تربط اهداف التدريب الميداني بين النظرية والتطبيق', 5);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'توافق التدريب الميداني مع التخصص', 6);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يوفر برنامج التدريب الميداني الفترة الزمنية الكافية للتطبيق', 7);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تساعدني المقررات الدراسية في تكوين فكرة واضحة عما ينبغي ان اقوم به في الجانب التطبيقي', 8);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'اكسبني برنامج التدريب الميداني المهارات الضرورية لمهمتي المستقبلية', 9);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'استفدت من برنامج التدريب الميداني', 10);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'الخبرة التي يقدمه التدريب التعاوني صقلت مهاراتي', 11);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'امكانيات ومهارات المدرب تتناسب مع التدريب الميداني', 12);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'يتسم مسؤول التدريب الميداني بالجدية', 13);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'توجد جدية في اجراءات التدريب الميداني', 14);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'مكان التدريب الميداني وتجهيزاته مناسبة', 15);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'توجد جدية في متابعة خطة التدريب الميداني وفاعليتها', 16);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'تعاون موظفي الجهة القائمة بالتدريب', 17);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'اتيح لي التوجيه الكافي فيما يخص بفرص الدراسة المستقبلية', 18);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'جودة التدريب الميداني مرضية بشكل عام', 19);
  insert into survey_questions (axis_id, text_ar, position) values (aid, 'التقييم العام', 20);
end $$;
